steps:
    - name: 'Uploading output.txt'
      command: 'echo "ciao!" > output.txt'
      artifact_paths:
        - 'output.txt'

    - wait

    - name: 'Downloading output.txt'
      command: 'buildkite-agent artifact download output.txt .'
